#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "${BLOCK_PATH:-"$shome/work"}/block/script/profile" ~
  source normalize  

  local hst_remote="${1}"; shift
  local loader="ssh $hst_remote"

  $loader true

  if [[ "$hst_remote" != "localhost" ]]; then
    local TX_GPG="$(gpg2 --card-status 2>/dev/null | awk '/General key info/ {print $NF}' | cut -d'<' -f2 | cut -d'>' -f1 || true)"
    if [[ -n "${TX_GPG}" ]]; then
      if $loader which gpg2; then
        gpg2 --export -a "$TX_GPG" | $loader gpg2 --import
        gpg2 --export-ownertrust | $loader gpg2 --import-ownertrust
        $loader gpg2 --check-trustdb
      fi
    fi
  fi &

  $loader tmux new -d || true

  wait
  tx "$hst_remote" "$@"
}

source sub "$BASH_SOURCE" "$@"
