#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "${BLOCK_PATH:-"$shome/work"}/block/script/profile" ~
  source normalize  

  local nm_key="${1}"; shift

  tx "$(consul kv get "${nm_key}")" "${nm_key}"
}

source sub "$BASH_SOURCE" "$@"
