#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "${BLOCK_PATH:-"$shome/work"}/block/script/profile" ~
  source normalize  

  local url="$1"; shift

  echo -n -e "\033]8;;${url}\007$*\033]8;;\007"
}

source sub "$BASH_SOURCE" "$@"
