#!/usr/bin/env bash

function main {
  set -efu

  cd
  source ".bash_profile"

  ln -nfs "${SSH_AUTH_SOCK}" "$HOME/.ssh/ssh_auth_sock"

  local nm_session="$1"; shift

  if tmux has-session -t "${nm_session}" 2>/dev/null; then
    tmux detach-client -s "${nm_session}" 2>/dev/null || true
    exec tmux -CC attach -t "${nm_session}"
  else
    txm start "${nm_session}" || true
    exec txm start "${nm_session}"
  fi
}

source sub "$BASH_SOURCE" "$@"
