#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure misc/tmux

  mkdir -p "$shome/bin"
  block compile bundler
  ln -nfs "$(bundle exec which tmuxinator)" "$shome/bin/"
}

main "$@"
