#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure misc/tmux

  block compile bundler

  mkdir -p "$shome/bin"
  ln -nfs ../vendor/bundle/bin/tmuxinator "$shome/bin/"
}

main "$@"
