#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure misc/tmux

  block compile bundler

  block compile pipenv install --three "$@"
  local pth_tmuxp="$(pipenv run which tmuxp)"

  mkdir -p "$shome/bin"
  ln -nfs "$pth_tmuxp" "$shome/bin/"
}

main "$@"
