#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_tmux="$(tmux -V 2>/dev/null || true)"
  jq -n --arg tmux "$ver_tmux" '{tmux: $tmux}'
}

version "$@"
