#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_tmux="0.0.1"
  jq -n --arg tmux "$ver_tmux" '{tmux: $tmux}'
}

version "$@"
